/*
 * lg_emoji.h - the emoji this firmware can draw, generated by tools/build_emoji_font.py.
 * Do not edit: the list must match the glyphs in the font, or a key draws nothing.
 *
 * Glyphs from Noto Emoji (monochrome), SIL Open Font License 1.1.
 */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(lg_font_emoji_20)
LV_FONT_DECLARE(lg_font_emoji_14)

#define LG_EMOJI_COUNT 48u

/* UTF-8, in keyboard order. */
static const char *const LG_EMOJI[LG_EMOJI_COUNT] = {
    "\xF0\x9F\x99\x82",   /* slight smile */
    "\xF0\x9F\x98\x83",   /* grin */
    "\xF0\x9F\x98\x82",   /* laughing */
    "\xF0\x9F\x98\x89",   /* wink */
    "\xF0\x9F\x98\x8D",   /* heart eyes */
    "\xF0\x9F\x98\x9B",   /* tongue */
    "\xF0\x9F\x98\x94",   /* sad */
    "\xF0\x9F\x98\xA2",   /* crying */
    "\xF0\x9F\x98\xA0",   /* angry */
    "\xF0\x9F\x98\xAE",   /* surprised */
    "\xF0\x9F\x98\xB0",   /* worried */
    "\xF0\x9F\x98\xB4",   /* sleeping */
    "\xF0\x9F\x91\x8D",   /* thumbs up */
    "\xF0\x9F\x91\x8E",   /* thumbs down */
    "\xF0\x9F\x91\x8C",   /* ok hand */
    "\xF0\x9F\x91\x8B",   /* wave */
    "\xF0\x9F\x99\x8F",   /* please */
    "\xF0\x9F\x92\xAA",   /* strong */
    "\xE2\x9D\xA4",   /* heart */
    "\xF0\x9F\x94\xA5",   /* fire */
    "\xE2\xAD\x90",   /* star */
    "\xE2\x9C\x85",   /* done */
    "\xE2\x9D\x8C",   /* no */
    "\xE2\x9D\x97",   /* important */
    "\xE2\x9A\xA0",   /* warning */
    "\xF0\x9F\x86\x98",   /* sos */
    "\xF0\x9F\x9B\x91",   /* stop */
    "\xF0\x9F\x9A\x91",   /* ambulance */
    "\xF0\x9F\x9A\x92",   /* fire engine */
    "\xF0\x9F\x91\xAE",   /* police */
    "\xE2\x9B\xBA",   /* tent */
    "\xF0\x9F\x8F\xA0",   /* home */
    "\xF0\x9F\x97\xBA",   /* map */
    "\xF0\x9F\xA7\xAD",   /* compass */
    "\xF0\x9F\x94\xA6",   /* torch */
    "\xF0\x9F\x94\x8B",   /* battery */
    "\xF0\x9F\x93\xB6",   /* signal */
    "\xF0\x9F\x93\x9E",   /* phone */
    "\xF0\x9F\x92\xAC",   /* talk */
    "\xF0\x9F\x95\x93",   /* clock */
    "\xF0\x9F\x8C\xA7",   /* rain */
    "\xE2\x98\x80",   /* sun */
    "\xF0\x9F\x8C\x99",   /* night */
    "\xE2\x9D\x84",   /* cold */
    "\xF0\x9F\x8D\x9C",   /* food */
    "\xE2\x98\x95",   /* hot drink */
    "\xF0\x9F\x9A\xB0",   /* water */
    "\xF0\x9F\x9A\xBD",   /* toilet */
};

#ifdef __cplusplus
}
#endif
