#!/usr/bin/env python3
"""Rewrite an lv_font_conv C font (format "lvgl", 4 bpp, uncompressed) as an lg_draw font (D55).

Keeps the bitmap, glyph table, and character maps, drops kerning (lg_draw does not kern), and
declares one `const lg_font_t` from the font's line height and base line.

  python tools/convert_font.py <lvgl font .c> <output .c> <symbol name> [header comment line ...]

The Montserrat fonts were converted once from LVGL 9.5's src/font/lv_font_montserrat_*.c;
tools/build_emoji_font.py calls this for the emoji fonts.
"""
import re
import sys
from pathlib import Path


def block(text, name):
    m = re.search(r"static[^;=\n]*\b" + re.escape(name) + r"\[\]\s*=\s*\{.*?\n\};", text, re.S)
    return m.group(0) if m else None


def number(text, field):
    m = re.search(r"\." + field + r"\s*=\s*(-?\d+)", text)
    if not m:
        sys.exit(f"no .{field} in the font")
    return int(m.group(1))


def convert(src_text, symbol, comments):
    if number(src_text, "bpp") != 4 or number(src_text, "bitmap_format") != 0:
        sys.exit("only 4 bpp uncompressed fonts are supported (lv_font_conv --bpp 4 --no-compress)")
    parts = []
    for name in ["glyph_bitmap", "glyph_dsc"]:
        b = block(src_text, name)
        if b is None:
            sys.exit(f"no {name} table")
        parts.append(b)
    for name in sorted(set(re.findall(r"\b((?:unicode_list|glyph_id_ofs_list)_\d+)\[\]", src_text))):
        parts.append(block(src_text, name))
    cmaps = block(src_text, "cmaps")
    if cmaps is None:
        sys.exit("no cmaps table")
    parts.append(cmaps)
    body = "\n\n".join(parts)
    body = body.replace("LV_ATTRIBUTE_LARGE_CONST ", "")
    body = body.replace("lv_font_fmt_txt_glyph_dsc_t", "lg_glyph_t")
    body = body.replace("lv_font_fmt_txt_cmap_t", "lg_font_cmap_t")
    body = body.replace("LV_FONT_FMT_TXT_CMAP_", "LG_FONT_CMAP_")
    if re.search(r"\blv_|\bLV_", body):
        sys.exit("an LVGL name is left in the tables")
    header = "/*\n * Generated by tools/convert_font.py. Do not edit.\n"
    for c in comments:
        header += f" * {c}\n" if c else " *\n"
    header += " */\n#include \"lg_font.h\"\n\n"
    tail = (f"\n\nconst lg_font_t {symbol} = {{\n"
            f"    .bitmap = glyph_bitmap,\n"
            f"    .glyphs = glyph_dsc,\n"
            f"    .cmaps = cmaps,\n"
            f"    .cmap_num = {number(src_text, 'cmap_num')},\n"
            f"    .bpp = 4,\n"
            f"    .line_height = {number(src_text, 'line_height')},\n"
            f"    .base_line = {number(src_text, 'base_line')},\n"
            f"}};\n")
    return header + body + tail


def main():
    if len(sys.argv) < 4:
        sys.exit(__doc__)
    src, out, symbol = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
    text = convert(src.read_text(encoding="utf-8"), symbol, sys.argv[4:])
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"{out}: {symbol}")


if __name__ == "__main__":
    main()
