#!/usr/bin/env python3
"""Generate firmware/common/lg_secrets.h with fresh random prototype keys.

The output file is gitignored. Every node and handheld in one prototype grid
must be built from the same lg_secrets.h, so generate it once and keep it.

  python tools/gen_secrets.py            create the file if it does not exist
  python tools/gen_secrets.py --update   add values introduced since the file was made, keeping every key
  python tools/gen_secrets.py --force    replace every key (all boards must then be reflashed)
"""
import hashlib
import hmac
import pathlib
import re
import secrets
import string
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "firmware" / "common" / "lg_secrets.h"

DISCRIMINATOR_BLOCK = """
/* 4-byte grid discriminator carried in node beacons: HKDF-SHA256(backbone key, "lg-disc").
 * Handhelds recognise nodes with this value and never reference the backbone key. */
#define LG_SECRET_DISCRIMINATOR {{ {values} }}
"""


def c_bytes(data):
    return ", ".join(f"0x{b:02x}" for b in data)


def discriminator(key):
    """RFC 5869 HKDF-SHA256 with an empty salt, as lg_hkdf_sha256 computes it on the nodes."""
    prk = hmac.new(b"", key, hashlib.sha256).digest()
    return hmac.new(prk, b"lg-disc" + b"\x01", hashlib.sha256).digest()[:4]


def create():
    alphabet = string.ascii_letters + string.digits
    passphrase = "".join(secrets.choice(alphabet) for _ in range(20))
    key = secrets.token_bytes(32)
    OUT.write_text(f"""/* Generated by tools/gen_secrets.py. DO NOT COMMIT. */
#pragma once

/* WPA2 passphrase for every node SoftAP in this prototype grid. */
#define LG_SECRET_WIFI_PASSPHRASE "{passphrase}"

/* 256-bit backbone key: ChaCha20-Poly1305 for node-to-node ESP-NOW frames. */
#define LG_SECRET_BACKBONE_KEY {{ {c_bytes(key)} }}
""" + DISCRIMINATOR_BLOCK.format(values=c_bytes(discriminator(key))), encoding="utf-8")
    print(f"wrote {OUT}")


def update():
    text = OUT.read_text(encoding="utf-8")
    if "LG_SECRET_DISCRIMINATOR" in text:
        print(f"{OUT} is up to date")
        return
    m = re.search(r"#define LG_SECRET_BACKBONE_KEY \{([^}]*)\}", text)
    key = bytes(int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]{2})", m.group(1))) if m else b""
    if len(key) != 32:
        sys.exit(f"{OUT} has no 32-byte LG_SECRET_BACKBONE_KEY; regenerate with --force")
    OUT.write_text(text.rstrip("\n") + "\n" + DISCRIMINATOR_BLOCK.format(values=c_bytes(discriminator(key))),
                   encoding="utf-8")
    print(f"added LG_SECRET_DISCRIMINATOR to {OUT}; keys unchanged")


if "--update" in sys.argv:
    if not OUT.exists():
        sys.exit(f"{OUT} does not exist; run without --update to create it")
    update()
elif OUT.exists() and "--force" not in sys.argv:
    print(f"{OUT} already exists; pass --update to add new values or --force to replace it "
          "(all boards must then be reflashed).")
else:
    create()
