#!/usr/bin/env python3
"""Generate firmware/common/lg_secrets.h with fresh random prototype keys.

The output file is gitignored. Every node and handheld in one prototype grid
must be built from the same lg_secrets.h, so generate it once and keep it.
"""
import pathlib
import secrets
import string
import sys

out = pathlib.Path(__file__).resolve().parent.parent / "firmware" / "common" / "lg_secrets.h"
if out.exists() and "--force" not in sys.argv:
    print(f"{out} already exists; pass --force to replace it (all boards must then be reflashed).")
    sys.exit(0)

alphabet = string.ascii_letters + string.digits
passphrase = "".join(secrets.choice(alphabet) for _ in range(20))
key = secrets.token_bytes(32)
key_c = ", ".join(f"0x{b:02x}" for b in key)

out.write_text(f"""/* Generated by tools/gen_secrets.py. DO NOT COMMIT. */
#pragma once

/* WPA2 passphrase for every node SoftAP in this prototype grid. */
#define LG_SECRET_WIFI_PASSPHRASE "{passphrase}"

/* 256-bit backbone key: ChaCha20-Poly1305 for node-to-node ESP-NOW frames. */
#define LG_SECRET_BACKBONE_KEY {{ {key_c} }}
""", encoding="utf-8")
print(f"wrote {out}")
